testapp/mysite/displayapi/urls.py
from django.urls import path, include 
from . import views

urlpatterns = [
   path('vo',views.ok),
    path('',views.home,name = 'home'),
]

testapp/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('polls/',include('polls.urls')),
    path("admin/", admin.site.urls),
    path('displayapi/',include('displayapi.urls')),
]

testapp/mysite/polls/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail,name='detail'),
    path('<int:question_id>/results/', views.results, name = 'results'),
    path('<int:question_id>/vote/', views.vote,name='vote'),
    
]

testapp/mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

testapp/mysite/displayapi/views.py
from django.shortcuts import render
import requests

# Create your views here.
def ok(request):
    return render(request,'ok.html')


def home(request):
    response=requests.get('https://www.boredapi.com/api/activity').json()
    print(response)
    return render(request,'home.html',{'response':response}) 

testapp/mysite/polls/views.py
from django.shortcuts import render

from django.http import HttpResponse
from .models import Question
from django.shortcuts import render
from django.http import Http404

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


from django.shortcuts import get_object_or_404, render


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

testapp/mysite/displayapi/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <string>Plz work my god </string>
    {{response}}
</body>
</html>

testapp/mysite/polls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>
<ul>
  {% for choice in question.choice_set.all %}
  <li>{{ choice.choice_text }}</li>
  {% endfor %}
</ul>

testapp/mysite/polls/templates/polls/index.html
{% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}
  <li>
    <a href="{% url 'polls:detail' question.id}"
      >{{ question.question_text }}</a
    >
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}